-- 코드를 입력하세요
SELECT A.AUTHOR_ID,AUTHOR_NAME,CATEGORY,SUM((SALES * PRICE)) AS TOTAL_SALES FROM BOOK_SALES S 
JOIN BOOK B ON B.BOOK_ID = S.BOOK_ID 
JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID 
WHERE YEAR(S.SALES_DATE) = 2022 AND MONTH(S.SALES_DATE) = 1
GROUP BY CATEGORY,AUTHOR_ID
ORDER BY AUTHOR_ID,CATEGORY DESC